import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
} from "@playwright/test/reporter";
import * as fs from "fs";
import * as path from "path";

/**
 * Minimal Markdown reporter.
 *
 * Writes a single Markdown summary of the whole run (totals + per-test table)
 * suitable for CI artifacts and GitHub step summaries.
 *
 * Output path can be set via the MD_REPORT_PATH env var.
 * Defaults to test-results/test-summary.md.
 */
class MarkdownReporter implements Reporter {
  private rows: {
    title: string;
    status: string;
    durationMs: number;
    project: string;
  }[] = [];
  private startedAt = 0;
  private outputFile: string;

  constructor(options: { outputFile?: string } = {}) {
    this.outputFile =
      options.outputFile ||
      process.env.MD_REPORT_PATH ||
      path.join("test-results", "test-summary.md");
  }

  onBegin(_config: FullConfig, _suite: Suite): void {
    this.startedAt = Date.now();
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    const titlePath = test.titlePath().filter(Boolean);
    // titlePath()[1] is the project name; drop it from the readable title.
    const project = test.parent.project()?.name ?? "";
    const readable = titlePath.filter((t) => t && t !== project).join(" › ");
    this.rows.push({
      title: readable,
      status: result.status,
      durationMs: result.duration,
      project,
    });
  }

  async onEnd(result: FullResult): Promise<void> {
    const total = this.rows.length;
    const passed = this.rows.filter((r) => r.status === "passed").length;
    const failed = this.rows.filter((r) => r.status === "failed").length;
    const timedOut = this.rows.filter((r) => r.status === "timedOut").length;
    const skipped = this.rows.filter((r) => r.status === "skipped").length;
    const durationS = ((Date.now() - this.startedAt) / 1000).toFixed(1);
    const passRate = total ? Math.round((passed / total) * 100) : 0;

    const statusIcon = (s: string): string =>
      s === "passed" ? "✅" : s === "skipped" ? "⏭️" : "❌";

    const lines: string[] = [];
    lines.push(`# Test Execution Summary`);
    lines.push("");
    lines.push(
      `**Overall result:** ${result.status === "passed" ? "✅ PASSED" : "❌ " + result.status.toUpperCase()}`,
    );
    lines.push(`**Date:** ${new Date().toISOString()}`);
    lines.push(`**Duration:** ${durationS}s`);
    lines.push("");
    lines.push(`| Metric | Count |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total | ${total} |`);
    lines.push(`| ✅ Passed | ${passed} |`);
    lines.push(`| ❌ Failed | ${failed} |`);
    lines.push(`| ⏱️ Timed out | ${timedOut} |`);
    lines.push(`| ⏭️ Skipped | ${skipped} |`);
    lines.push(`| Pass rate | ${passRate}% |`);
    lines.push("");
    lines.push(`## Test Results`);
    lines.push("");
    lines.push(`| # | Test | Status | Duration |`);
    lines.push(`|---|------|--------|----------|`);
    this.rows.forEach((r, i) => {
      lines.push(
        `| ${i + 1} | ${r.title} | ${statusIcon(r.status)} ${r.status} | ${(r.durationMs / 1000).toFixed(1)}s |`,
      );
    });
    lines.push("");
    lines.push(`_Generated by the Playwright Markdown reporter._`);

    const content = lines.join("\n") + "\n";
    fs.mkdirSync(path.dirname(this.outputFile), { recursive: true });
    fs.writeFileSync(this.outputFile, content, "utf-8");

    // Also append to the GitHub Actions step summary when running in CI.
    if (process.env.GITHUB_STEP_SUMMARY) {
      fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, content, "utf-8");
    }

    // eslint-disable-next-line no-console
    console.log(`\nMarkdown report written to ${this.outputFile}`);
  }
}

export default MarkdownReporter;
